### ISSUE TITLE
An error occured :'(

### ISSUE THREAD

**Issue by RightHandLeft** [cptpingu/poe-stash#2]
template: parts\itemdesc.tmpl:249:57: executing "itemdesc" at <div .Total .Progress>: error calling div: runtime error: integer divide by zero

**Comment by cptpingu** [comment]
Thanks for bug report! I've just committed a fix. I will make a new release as soon as possible.

**Comment by cptpingu** [comment]
I updated the release. Thank you a lot for the bug report!
