### ISSUE TITLE
Unique Stash tab not showing correctly.

### ISSUE THREAD

**Issue by edenhack** [cptpingu/poe-stash#3]
I believe this is GGG side however the uniques tab only shows as a standard stash tab and is empty, as vs being a specialized screen with the categories of uniques and such. Using most recent build as of current post date.

**Comment by cptpingu** [comment]
Thank you for the report!

I don't think this is a GGG issue like with the map tab. I don't own the uniques tab, so I never had the chance to handle it ;).
If you can share me both the json returned by the api and the html generated on the official website, I could start to understand how it works, and add it.

**Comment by cptpingu** [comment]
A friend of mine has the unique tab. So, I took a look at it. It seems the unique stash tab is not handled by GGG. There are aware of the bug: https://www.pathofexile.com/forum/view-thread/1733474#p13674912.
I put a placeholder to explain it better.
