### ISSUE TITLE
PoE 3.15 StashTab.fragmentLayout problem

### ISSUE THREAD

**Issue by ylemarie** [cptpingu/poe-stash#4]
Can't start app with PoE 3.15, seem to be a problem with fragment stash.
Server & Client mode :

ᐅ ./poe-stash-cli --interactive

Account: Le********
PoE Sessid: 9fdf*********************
League (empty = standard): expedition
Realm (empty = pc): 
can't scrap data json: cannot unmarshal array into Go struct field StashTab.fragmentLayout of type models.Layout

**Comment by cptpingu** [comment]
Thx for the report!
It should be fixed. I'm not actively maintaining it. Too much work for so few users. So don't expect a perfect rendering.
